fixed indentation

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,8 +22,7 @@ concurrency:
 
 jobs:
   # Single deploy job since we're just deploying
-
-    setup:
+  setup:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -31,27 +30,29 @@ jobs:
       - name: Set up Node
         uses: actions/setup-node@v3
         with:
-        node-version: 18
-        cache: 'npm'
+          node-version: 18
+          cache: 'npm'
       - name: Install dependencies
         run: npm install
 
   build:
-      needs: setup # Wait for the setup job to complete
-      steps: 
-          - name: Build
-            run: npm run build
-    - name: Check if build succeeded
-      run: |
-        if [ -d "dist" ]; then
-          echo "Build successful!"
-        else
-          echo "Build failed!"
-          exit 1 # Exit the job with an error code
-        fi
+    needs: setup # Wait for the setup job to complete
+    runs-on: ubuntu-latest
+    steps:
+      - name: Build
+        run: npm run build
+      - name: Check if build succeeded
+        run: |
+          if [ -d "dist" ]; then
+            echo "Build successful!"
+          else
+            echo "Build failed!"
+            exit 1 # Exit the job with an error code
+          fi
 
   test:
     needs: build
+    runs-on: ubuntu-latest
     steps:
       - name: Run tests
         run: npm test
@@ -61,14 +62,15 @@ jobs:
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
-      steps:
-        - name: Setup Pages
-          uses: actions/configure-pages@v3
-        - name: Upload artifact
-          uses: actions/upload-pages-artifact@v1
-          with:
-            # Upload dist repository
-            path: './dist'
-        - name: Deploy to GitHub Pages
-          id: deployment
-          uses: actions/deploy-pages@v1
+    runs-on: ubuntu-latest
+    steps:
+      - name: Setup Pages
+        uses: actions/configure-pages@v3
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          # Upload dist repository
+          path: './dist'
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
