changed deployment to build and test before deploy to gh pages

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,5 @@
 # Simple workflow for deploying static content to GitHub Pages
-name: Deploy static content to Pages
+name: Build, test and deploy to GH pages
 
 on:
   # Runs on pushes targeting the default branch
@@ -22,10 +22,8 @@ concurrency:
 
 jobs:
   # Single deploy job since we're just deploying
-  deploy:
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
+
+    setup:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -33,19 +31,44 @@ jobs:
       - name: Set up Node
         uses: actions/setup-node@v3
         with:
-          node-version: 18
-          cache: 'npm'
+        node-version: 18
+        cache: 'npm'
       - name: Install dependencies
         run: npm install
-      - name: Build
-        run: npm run build
-      - name: Setup Pages
-        uses: actions/configure-pages@v3
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v1
-        with:
-          # Upload dist repository
-          path: './dist'
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v1
+
+  build:
+      needs: setup # Wait for the setup job to complete
+      steps: 
+          - name: Build
+            run: npm run build
+    - name: Check if build succeeded
+      run: |
+        if [ -d "dist" ]; then
+          echo "Build successful!"
+        else
+          echo "Build failed!"
+          exit 1 # Exit the job with an error code
+        fi
+
+  test:
+    needs: build
+    steps:
+      - name: Run tests
+        run: npm test
+
+  deploy:
+    needs: test
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+      steps:
+        - name: Setup Pages
+          uses: actions/configure-pages@v3
+        - name: Upload artifact
+          uses: actions/upload-pages-artifact@v1
+          with:
+            # Upload dist repository
+            path: './dist'
+        - name: Deploy to GitHub Pages
+          id: deployment
+          uses: actions/deploy-pages@v1
